### ISSUE TITLE
Is there a pure Java version of this lib? (without kotlin language)

### ISSUE THREAD

**Issue by yingzhuo** [akkinoc/yaml-resource-bundle#60]
## Is there a pure Java version of this lib?

For some reasons, I can't use kotlin in my production-env. : (

**Comment by akkinoc** [comment]
Thank you for your question.

Currently this is only implemented in Kotlin.

v1.x doesn't depend on Kotlin, so it might help you.
(There are no plans to update the pure Java version in the future.)

**Comment by yingzhuo** [comment]
@akkinoc

I gave up for yaml-resource-bundle. properties + native2ascii is ok for me.
Thank you all the same. Love from Shanghai, China.
